// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // The app NEVER uses Supabase Auth sessions (custom localStorage auth +
    // Firebase for credentials). Without this, a stray Supabase magic-link
    // email could land with tokens in the URL hash and silently log the
    // visitor in as a session-less "client" — which is exactly the bug where
    // clicking the verification email skipped phone+DOB and showed the
    // email username in the top bar.
    detectSessionInUrl: false,
  }
});