import { useState, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Lightbulb, Save, Eye, EyeOff, BrainCircuit, Loader2 } from "lucide-react";
import { toast } from "sonner";

export default function Tips() {
  const qc = useQueryClient();
  const [apiKey, setApiKey] = useState("");
  const [showKey, setShowKey] = useState(false);

  // Fetch the existing Gemini API key from the daily_tips table
  const { data: savedKey = "", isLoading } = useQuery({
    queryKey: ["admin-gemini-key"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("daily_tips")
        .select("text");
      if (error) return "";
      const row = (data ?? []).find((t) => t.text.startsWith("gemini_api_key:"));
      return row ? row.text.replace("gemini_api_key:", "") : "";
    },
  });

  // Load the saved key into local state
  useEffect(() => {
    if (savedKey) {
      setApiKey(savedKey);
    }
  }, [savedKey]);

  // Mutation to save the API key
  const save = useMutation({
    mutationFn: async () => {
      // 1. Delete all existing rows starting with gemini_api_key:
      const { error: deleteError } = await supabase
        .from("daily_tips")
        .delete()
        .like("text", "gemini_api_key:%");
      if (deleteError) throw deleteError;

      // 2. Insert the new key if provided
      const trimmedKey = apiKey.trim();
      if (trimmedKey) {
        const { error: insertError } = await supabase
          .from("daily_tips")
          .insert({
            text: `gemini_api_key:${trimmedKey}`,
            active: true,
            sort_order: 0,
          });
        if (insertError) throw insertError;
      }
    },
    onSuccess: () => {
      toast.success(apiKey.trim() ? "Gemini API Key saved successfully!" : "Gemini API Key removed");
      qc.invalidateQueries({ queryKey: ["admin-gemini-key"] });
      qc.invalidateQueries({ queryKey: ["daily-tips"] });
    },
    onError: (e) => {
      toast.error(e instanceof Error ? e.message : "Failed to save API key");
    },
  });

  return (
    <div className="space-y-6 max-w-2xl">
      <header>
        <h1 className="font-display text-3xl text-foreground flex items-center gap-2">
          <BrainCircuit className="h-8 w-8 text-primary" /> Daily wellness tips (AI)
        </h1>
        <p className="mt-1 text-muted-foreground">
          Wellness tips shown on the client Health page are now automatically generated by Gemini AI every 24 hours.
        </p>
      </header>

      <Card className="rounded-2xl shadow-card p-5 md:p-6 space-y-4">
        <div className="flex items-center gap-2">
          <Lightbulb className="h-5 w-5 text-fv-orange" style={{ color: "#f0a720" }} />
          <p className="font-semibold text-sm">Gemini AI Configuration</p>
        </div>

        <p className="text-xs text-muted-foreground leading-relaxed">
          Provide your Google Gemini API key. Once set, the system will use it to securely query Gemini for a fresh, random wellness tip each day. Tips are cached locally on client devices for 24 hours to ensure high performance and minimize API requests.
        </p>

        <div className="space-y-2">
          <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
            Gemini API Key
          </label>
          <div className="relative">
            <Input
              type={showKey ? "text" : "password"}
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
              placeholder="AIzaSy..."
              className="pr-10 h-11 rounded-xl"
              disabled={isLoading || save.isPending}
            />
            <button
              type="button"
              onClick={() => setShowKey(!showKey)}
              className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
              disabled={isLoading || save.isPending}
            >
              {showKey ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
            </button>
          </div>
        </div>

        <div className="flex items-center justify-between pt-2">
          <Button
            onClick={() => save.mutate()}
            disabled={isLoading || save.isPending}
            className="rounded-xl px-5 h-11 gap-2"
          >
            {save.isPending ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Save className="h-4 w-4" />
            )}
            {save.isPending ? "Saving..." : "Save Key"}
          </Button>

          {savedKey && (
            <Badge variant="secondary" className="bg-green-500/10 text-green-600 border-none px-2.5 py-1 text-[11px]">
              AI Generation Active
            </Badge>
          )}
        </div>
      </Card>
    </div>
  );
}
